Main svc
LisaGavryushkina/java-explore-with-me pull request #4
Opened 2023-10-09 16:27 UTC by LisaGavryushkina

2023-10-10 03:31 UTC, EugeneLenkevich requested changes
Привет, Елизавета! Спасибо за PR.

Отличная работа! :)
Вижу в работе множество продвинутых вещей, что не может не радовать. Хотелось бы производительность несколько улучшить, есть два сквозных момента по всем сервисам и сущностям: с транзакциями и лишними запросами, которые будет порождать toString, проверь, пожалуйста :)

2023-10-10 03:31 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/category/CategoryServiceImp.java
> +    public List<CategoryDto> getCategories(int from, int size) {
Над сервисом стоит аннотация @Transactional, все методы будут выполняться в транзакциях, это правильно для методов, которые изменяют данные однако для методов , которые только читают данные - это лишние накладные расходы. 
Тут бы или добавить аннотацию @Transactional(readonly=true) или вовсе перевесить аннотацию на методы, изменяющие данные (вставка, удаление и изменение) :)

![image](https://github.com/LisaGavryushkina/java-explore-with-me/assets/109306643/9267ca5a-7be8-4a9b-aec4-8500b6fe7083)

2023-10-10 03:31 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/event/Event.java
> +    @ManyToOne(fetch = FetchType.LAZY)
Моментик с производительностью. У нас есть LAZY-связи, у нас есть метод toString, который строится по всем полям. Соответственно при его вызове у нас будут инициированы дополнительные SQL-запросы. Если же мы перебираем целый список, то у нас будет много запросов и БД не особо эту дополнительную нагрузку оценит  :)

1. Их можно исключить из toString
2. Эти связи можно сделать EAGER, по умолчанию это значение и стоит. Ленивыми обычно делают связанные коллекции

PS по другим сущностям такая же история, посмотри, пожалуйста :)


![image](https://github.com/LisaGavryushkina/java-explore-with-me/assets/109306643/9be701df-1674-41af-b2bc-dc571720bed3)

2023-10-10 03:31 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +                .sorted(sort == SortEventsBy.EVENT_DATE ?
А сортировку а сортировку и отборку n-значений не получится сделать на уровне БД? :)

2023-10-10 19:19 UTC, LisaGavryushkina commented on ewm-service/src/main/java/ru/practicum/ewm/category/CategoryServiceImp.java
> +    public List<CategoryDto> getCategories(int from, int size) {
Перевесила аннотацию на методы, изменяющие данные

2023-10-10 19:20 UTC, LisaGavryushkina commented on ewm-service/src/main/java/ru/practicum/ewm/event/Event.java
> +    @ManyToOne(fetch = FetchType.LAZY)
Сделала связи EAGER

2023-10-10 19:27 UTC, LisaGavryushkina commented on ewm-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +                .sorted(sort == SortEventsBy.EVENT_DATE ?
Тут, к сожалению, есть такой неудобный момент - вариант сортировки по кол-ву просмотров, которые мы запрашиваем у сервиса статистики. Из-за этого я не могу сортировать и отбирать нужное количество событий в бд (тк там нет данных о просмотрах и без первоначальной сортировки отбор событий по from и size получится некорректным). Как я понимала, у меня было два варианта: либо разветвить все на два if, где в одном случае при сортировке по дате я смогла бы все это сделать в бд во время запроса событий, а в случае с сортировкой по кол-ву просмотров пришлось бы сделать так, как у меня сейчас. Я решила объединить оба случая и сделать все в соответствии с ограничивающим фактором, потому что подумала, что это будет не так страшно с точки зрения производительности

2023-10-11 03:30 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +                .sorted(sort == SortEventsBy.EVENT_DATE ?
А, ок, пусть так будет.

Вообще, как один из вариантов, часто реплицируют данные из другого сервиса в локальной БД каким то образом (данные периодически выгребает и сохраняет задача по крону или БД синхронизируется через брокер сообщений) и делают нормальные запросы к локальной БД

Там много способов, хотел ссылку найти, но везде все так сложно объясняют :)

https://qna.habr.com/q/309740

2023-10-11 03:31 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-10-11 11:02 UTC, merged